name: Codeflash

on:
  pull_request:
  workflow_dispatch:

jobs:
  optimize:
    name: Optimize new code in this PR
    if: ${{ github.actor != 'codeflash-ai[bot]' }}
    runs-on: ubuntu-latest
    env:
      CODEFLASH_API_KEY: ${{ secrets.CODEFLASH_API_KEY }}
      CODEFLASH_PR_NUMBER: ${{ github.event.number }}
      PYTHONIOENCODING: "utf8"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.27"

      - name: uv setup
        run: uv export --only-dev | uv pip sync -

      - name: Run Codeflash to optimize code
        id: optimize_code
        run: |
          uv run codeflash